class configParams:
	PAGE_ACCESS_TOKEN = "EAAMYeSx5DKEBAJbIZCw9mPoFhJC4UKnMvNCMmmmbIIyKQdBSWZCwdXUyKQ9F8i8KNFTkTayyAaROJ4pvwrmIS1SwhLL6SJP3i0oXFMPSS9L7KTnMnw9iBJQDveSjNJcZCwyqZAofyogHullOdbWDpctQ7l6EcCCZBhEDDmhxa8AZDZD"
	APP_SECRET = ""
	VALIDATION_TOKEN = "password_is_password"
	SERVER_URL = ""
