class configParams:
	PAGE_ACCESS_TOKEN = "EAAMYeSx5DKEBANAZApjsLROb70HZC0wMl6VdS98xNsxsB88D9BSHsnJCaPAgZCxVjxsGc1KtBot5GFQSupZC9Sfp7A2xbZBiEDXYyMitZCA8wBtIWF8oChyKfzGWO1UMvLtWEFVgW8fBtJSWZCZBtqdRR0nxqqtTFVU5ovBZC2AZAVFQZDZD"
	APP_SECRET = ""
	VALIDATION_TOKEN = "password_is_password"
	SERVER_URL = ""
